export const APP_LIMITS = {
  THREADS_PER_USER_PER_DAY: 20,

  MAX_THREAD_TITLE_LENGTH: 200,
  MAX_THREAD_CONTENT_LENGTH: 6000,

  MAX_COMMENT_LENGTH: 3000,

  MAX_SOURCES_PER_THREAD: 5,
  MAX_SOURCE_TITLE_LENGTH: 200,
  MAX_SOURCE_CONTENT_LENGTH: 30000,
  MAX_SOURCE_PDF_SIZE_BYTES: 5 * 1024 * 1024,

  MAX_AI_QUESTION_LENGTH: 2000,
  DEFAULT_AI_RETRIEVAL_LIMIT: 5,
  MAX_AI_RETRIEVAL_LIMIT: 10,
  MAX_AI_QUESTIONS_PER_USER_PER_DAY: 5,

  DEFAULT_THREAD_PAGE_SIZE: 20,
  MAX_THREAD_PAGE_SIZE: 20,
  MAX_THREAD_SEARCH_LENGTH: 200,
} as const;
